# Generated by Django 4.2.9 on 2024-01-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_ride_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CANCELLED', 'CANCELLED'), ('COMFIRMED', 'COMFIRMED'), ('PROGRESS', 'PROGRESS'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=15),
        ),
    ]
