# Generated by Django 4.2.9 on 2024-01-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='NULL', help_text='User Name', max_length=64),
        ),
    ]
