# Generated by Django 4.2.9 on 2024-01-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_sharegroupnumberrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CANCELLED', 'CANCELLED'), ('CONFIRMED', 'CONFIRMED'), ('PROGRESS', 'PROGRESS'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=15),
        ),
    ]
